### ISSUE TITLE
最長道路的解答供你參考

### ISSUE THREAD

**Issue by Kashionz** [creeper531100/2023-cyutcsie-exam#1]
上班看GitHub碰巧滑到你的Repo
我幾年前有在Gist上放過我自己的解答
可以給你參考一下(應該是cyut29.cpp)
https://gist.github.com/Kashionz/2430b7408ae6193e832365535f953ecb

你再看看要不要更新到你的Repo裡面
保齡球那題你也可以參考一下
不過我的看起來蠻狗屎的lol

**Comment by creeper531100** [comment]
謝謝學長的提供🥺
沒想到這邊竟然也能遇到學長，太驚訝了
我會在把題目他更新上去我的github上面
真的太感謝你了！！

Kashionz ***@***.***>於 2023年12月1日 週五，12:05寫道：
